<?php
/**
 * @file
 * A block module that displays recent blog and forum posts.
 *
 * Implements hook_help().
 *
 * Displays help and module information.
 *
 * @param path
 *   Which path of the site we're using to display help
 * @param arg
 *   Array that holds the current path as returned from arg() function
 */
function homepage_preprocess_page(&$variables) {
}

/**
 * Implements hook_menu().
 */
function homepage_menu() {
  $items = array();

  $items['admin/custom_tab/custom_homepage'] = array(
    'title' => 'Custom homepage',
    'type' => MENU_NORMAL_ITEM,
    'access arguments' => array('access administration pages'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('homepage_form'),
  );

  $items['custom_homepage'] = array(
    'title' => variable_get('custom_homepage','Custom homepage'),
    'page callback' => 'homepage_render_page',
    'access arguments' => array('access homepage content'),
    'type' => MENU_NORMAL_ITEM, // Will appear in Navigation menu.
  );

  return $items;
}

function homepage_form($form, &$form_state) {
  $form['custom_homepage'] = array(
    '#type' => 'textfield',
    '#title' => t('Title'),
    '#default_value' => variable_get('custom_homepage', 'Custom homepage'),
    '#size' => 100,
    '#maxlength' => 100,
    '#required' => TRUE,
  );

  return system_settings_form($form);
}

/**
 * Implements hook_theme().
 */
function homepage_theme($existing, $type, $theme, $path) {
    return array(
    'custom_homepage_theme' => array(
      'variables' => array('locations' => null),
      'template' => 'templates/custom_homepage'
    )
  );
}

function homepage_locations() {
  $location_home_id = taxonomy_vocabulary_machine_name_load('location');
  $locations_home = entity_load('taxonomy_term', FALSE, array('vid' => $location_home_id->vid));

  $locs_home = array();

  foreach ($locations_home as $loc_home) {
    $sorted_teams = array();
    $query = db_select('field_data_field_team_location','n')
      ->fields('n', array('entity_id') )
      ->condition('field_team_location_tid', $loc_home->tid);

    $teams_entity_ids = $query->execute();

    foreach ($teams_entity_ids as $id) {

      $sorted_teams[] = taxonomy_term_load($id->entity_id);
    }

    $loc_home->teams = $sorted_teams;
    $locs_home[] = $loc_home;
  }

  return $locs_home;
}

function homepage_render_page() {
  $output = array(
    '#theme' => 'custom_homepage_theme',
    '#type' => 'markup',
    '#locations' => homepage_locations()
  );

  return $output;
}

/**
 * Implements hook_permission().
 */
function homepage_permission() {
  return array(
    'access homepage content' => array(
      'title' => t('Access content for the homepage module'),
    )
  );
}

